spring:
  application:
    name: currency-exchange-service
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    default-schema: currency_exchange_service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;
    username: sa
  h2.console.enabled: true
  jpa:
    properties:
      hibernate:
        default_schema: currency_exchange_service
    hibernate:
      ddl-auto: validate

logging:
  level:
    liquibase: INFO


server:
  port: 8000
  servlet.context-path: /
